name: audit

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-09-08
          override: true

      - name: Install Cargo Audit
        run: cargo install cargo-audit

      - name: Check for vulnerabilities
        id: check_vulnerabilities
        run: cargo audit
        continue-on-error: true

      - name: Audit Failure
        if: ${{ steps.check_vulnerabilities.outcome == 'failure' }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ steps.check_vulnerabilities.outcome }}
          title: "Audit"
          content: "PIC:<shouki#3158>"
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png

      - name: Final status
        if: ${{ steps.check_vulnerabilities.outcome == 'failure' }}
        run: exit 1
