name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        id: build
        run: cargo build --verbose
        continue-on-error: true

      - name: Discord Message Notify
        if: ${{ steps.build.exitcode != 'success'}}
        uses: appleboy/discord-action@0.0.3
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#48f442"
          username: "GitHub Actions"
          args: ${{ steps.build.exitcode}} build is not succeeded.

      - name: Fail
        if: failure()
        run: exit 1
