name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        id: build
        run: cargo build --verbose
        continue-on-error: true

      - name: Build Failure
        if: ${{ steps.build.outcome == 'failure' }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ steps.build.outcome }}
          title: "Build"
          description: "Build failed."
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png

      - name: Final status
        if: ${{ steps.build.outcome == 'failure' }}
        run: exit 1
