name: security-audit

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '25 * * * *'

jobs:
  security_audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-09-08
          override: true

      - name: Install Cargo Audit
        run: cargo install cargo-audit

      - name: Check for vulnerabilities
        id: check_vulnerabilities
        run: cargo audit
        continue-on-error: true

      - name: Discord Message Notify
        if: ${{ steps.check_vulnerabilities.exitcode != 'success'}}
        uses: appleboy/discord-action@0.0.3
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#48f442"
          username: "GitHub Bot"
          args: The ${{ github.event_name }} event triggered.
        run: exit 1
